# Generated by Django 3.1.1 on 2020-09-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Home'), ('2', 'Personal'), ('3', 'Work'), ('4', 'Fitness'), ('5', 'Medication')], default=1, max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
