# Generated by Django 3.1.1 on 2020-09-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='colour',
            field=models.CharField(default=123456, max_length=7),
            preserve_default=False,
        ),
    ]
